/* Generated By:JavaCC: Do not edit this line. CabegConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CabegConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int THEN = 6;
  /** RegularExpression Id. */
  int ELSE = 7;
  /** RegularExpression Id. */
  int LET = 8;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int PRINT = 12;
  /** RegularExpression Id. */
  int RBR = 13;
  /** RegularExpression Id. */
  int LBR = 14;
  /** RegularExpression Id. */
  int INIT = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int NUMBER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int ID = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"let\"",
    "\"in\"",
    "\"end\"",
    "\"var\"",
    "\"print\"",
    "\")\"",
    "\"(\"",
    "\":=\"",
    "\",\"",
    "<NUMBER>",
    "<DIGIT>",
    "<ID>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
